language: node_js
node_js:
        - node
        - lts/*
env:
 - CXX=g++-4.9 # https://github.com/digitalbazaar/jsonld.js/issues/254
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-4.9
